---
AWSTemplateFormatVersion: 2010-09-09
Description: S3 Stack

Resources:
  SAMArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub alexa-sampler-sam-artifacts-${AWS::AccountId}-${AWS::Region}

Outputs:
  SAMArtifactBucketName:
    Value: !Ref SAMArtifactBucket
